### ISSUE TITLE
Close button image is too large

### ISSUE THREAD

**Issue by Yakumo-Yukari** [thomas-kammerer/elementary-x2#1]
![2020-07-09 16 13 34](https://user-images.githubusercontent.com/12076232/87015047-77dcc600-c1ff-11ea-8acb-f8d4d9df0d88.png)

Where does the button size need to be adjusted?

**Comment by thomas-kammerer** [comment]
Do you mean the image inside the buttons?

That would be: `-gtk-icon-transform: scale(.8);`

**Comment by Yakumo-Yukari** [comment]
> Do you mean the image inside the buttons?
> 
> That would be: `-gtk-icon-transform: scale(.8);`

Thank you
